url: https://the-whole-story.whatsnous.com
sitename: 'The Whole Story Podcast, produced by Nous Entertainment'
description: 'The Whole Story is a podcast modeled after that panel discussion at storytelling festivals that you always miss. '
mission_statement: "We are storytellers who celebrate the strength and depth of the human intellect and its ability to create joy as well as enact change. We use film – including theatrical, feature-length, digital and television formats – as our vehicle for distributing inspiring narratives and entertaining stories."
itunesLink: https://itunes.apple.com/us/podcast/the-whole-story-podcast/id1106041222 
feedLink: index.xml
categories:
  - podcast
  - updates

type:
  - guest
  - staff
  - executive

podcast_url: http://the-whole-story.whatsnous.com
podcast_album_art: /assets/img/cover-itunes-the-whole-story.png
podcast_title: The Whole Story Podcast
podcast_owner: Nous Entertainment
podcast_email: ashernovek@gmail.com
podcast_category: Comedy
podcast_subcategory_one: Arts
podcast_subcategory_two: Society and Culture
podcast_explicit: "no"
podcast_author: Asher Novek
podcast_description: The Whole Story is a podcast modeled after that panel discussion at storytelling festivals that you always miss.
podcast_summary: "Asher and Julia talk with the most influential and inspirational storytellers and producers on the scene today.  They get to the nitty gritty of storytelling, discuss the words behind the words and dissect what makes a storyteller a storyteller.  You’ve heard the stories, now get the whole story about who they are, what makes them tick, and where their stories come from.
"
podcast_subtitle: "The Whole Story, storytelling podcast"



#Jekyll Options
# if using more than one Jekyll instance on your local machine
# port: 4001
# paginate tells Jekyll how many posts per page
# paginate: 1
# Permalinks
permalink:  pretty
# Dependencies
#Pages - store all pages in the _pages directory
include: ['_pages', '_cms.html']
relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules']

gems:
  - jekyll-seo-tag
sass:
  style: :compressed
  sass_dir: assets/css

# dev options (true/false)
# if site is in production, 'production: true'
production: true

include_addthis_sharing: false
bust_css_cache: true

# options (data)
google_analytics_id: UA-51919693-6
disqus_id:
addthis_id:
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:

# options (social)
# facebook_id:
twitter_id: budparr

# navigation options - effects layout/default. May also need options set in sass files
include_nav-top: true
include_nav-side-left: false
include_nav-side-right: false

future: true
collections:
  contributors:
    output: false
    permalink: '/:collection/:path/'


# DEFAULTS
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      splash_image: splash-the-whole-storyx500.png
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      splash_image: splash-the-whole-storyx500.png

compress_html:
  ignore:
    envs: [development]
  profile: false
